### ISSUE TITLE
User Feedback in PlayerActivity

### ISSUE THREAD

**Issue by ctriley** [speakr-uconn/speakr#3]
We need feedback for the user. When adding a song to the queue, a box should appear that says "sending" and have some animation. Additionally, when hitting play or pause, "working" or some other on screen indication should appear.

**Comment by rdp11005** [comment]
if it's in an asynctask, can be done in onProgressUpdate() method in the task

**Comment by ctriley** [comment]
You can actually call the UI thread from anywhere provided you have the context. 

``` java
Handler mainHandler = new Handler(context.getMainLooper());
    mainHandler.post(new Runnable() {
        @Override
            public void run() {
                // put UI code here.
            }
    });
```
